version: "3.9"
services:
  db:
    build:
      context: ./docker
      dockerfile: db.Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
    hostname: "spring-17-db"