spring:
  main:
    allow-circular-references: true
  data:
    mongodb:
      database: new-test
      port: 27017
      host: localhost

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ot.homework5plus.rushm.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local