spring:
  application:
    name: rus-hm
  config:
    activate:
      on-profile: docker

server:
  servlet:
    encoding:
      charset: UTF-8

management:
  web:
    exposure:
      include: "*"
  endpoint:
    logfile:
      enabled: true
    health:
      show-details: always

resilience4j.bulkhead:
  instances:
    commentService:
      maxWaitDuration: 1500ms
      maxConcurrentCalls: 30
    authService:
      maxWaitDuration: 1500ms
      maxConcurrentCalls: 30
    bookService:
      maxWaitDuration: 1500ms
      maxConcurrentCalls: 30
    authorService:
      maxWaitDuration: 1500ms
      maxConcurrentCalls: 30
    genreService:
      maxWaitDuration: 1500ms
      maxConcurrentCalls: 30
resilience4j.circuitbreaker:
  instances:
    authService:
      slidingWindowSize: 10
      registerHealthIndicator: true
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      failureRateThreshold: 50
      minimumNumberOfCalls: 20
      eventConsumerBufferSize: 10
      waitDurationInOpenState: 50s

logging:
  file:
    name: spring-project/logs/spring-project.log
  level:
    ROOT: INFO
    org.springframework: INFO
    org.springframework.transaction: INFO
    org.springframework.security: INFO
    io.github.resilience4j: INFO

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    initialization-mode: always
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true