spring:
  main:
    allow-circular-references: true
  data:
    mongodb:
      database: database_test
      port: 27017
      host: localhost

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ot.homework5plus.rushm.changelogs

logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    org.springframework.transaction: INFO
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG